### ISSUE TITLE
(2) syntax of key strokes

### ISSUE THREAD

**Issue by dandrewstewart** [panavrin/live-writing-osc#10]
In Max, I've been struggling to isolate the final value (the "content", or "method") from the "containers".  Instead of the syntax, /added/line/position/key_stroke, could we convert the method /key-stroke into the argument for the OSC address:   /added/line/position key_stroke.  In other words, instead of /added/1/1/A, we would have /added/1/1 A.  The "A" is the argument (i.e., a space between the OSC address and the argument).  The OSC objects in Max (or in my case, I am using Jamoma), work best is the OSC message ends with an actual argument.  I'm still working on it, with the [regexp] in Max, though

**Comment by panavrin** [comment]
this is not difficult. I will do it right away.

**Comment by panavrin** [comment]
Done!

**Comment by dandrewstewart** [comment]
Bravo.  Thanks so much !!
