### ISSUE TITLE
loudness of voice samples on page 3

### ISSUE THREAD

**Issue by dandrewstewart** [panavrin/live-writing-osc#11]
If possible, could you increase the voice samples on page 3 by, say, 3 dB?

**Comment by panavrin** [comment]
I increased the amplitude of chatter_amp_3db.mp3 by 3dB

**Comment by dandrewstewart** [comment]
I guess this is an audio file I can also manipulate, correct (chatter_amp_3db.mp3)?  So, when you changed the sound intensity, did you simply modify the actual audio file?

**Comment by panavrin** [comment]
yes. however it can be tricky to update the file in the github repo. How do you update the new version? do you download the whole thing and replace it? 

If so your local change will be lost. To change the file github repo directly, you can upload the file in the folder: 

https://github.com/panavrin/live-writing-osc/tree/master/public/sound

**Comment by dandrewstewart** [comment]
Thanks for this info.  As you modify the software, I have been downloading the whole thing each time – it's very light – instead of cloning.  I assume that if I clone (creating one cloned repository on my computer), I can link the repository (on my computer) to github.com, correct?  And then, any updates that are uploaded to github, will be applied to the clone of my computer, correct?  I thought about this, but decided to copy the whole project each time.  What do you think?

I'll practice a bit more before I adjust the loudness of the crowd audio file.  As all of the LW audio runs through Ableton, I can also adjust levels in real time, in Ableton – but then, "ALL" LW writing levels will be adjusted (e.g., if I lower the crowd samples,  I also lower the key stroke sounds). I am already EQ-ing LW sounds to isolate the sounds I want.  This is also one reason why I'd like to explore multi-channel output from Chrome, but that'll be another project.  All my best

**Comment by panavrin** [comment]
I assume that if I clone (creating one cloned repository on my computer), I can link the repository (on my computer) to github.com, correct? 
**yes.** 
And then, any updates that are uploaded to github, will be applied to the clone of my computer, correct?
**Yes. If you `git pull`**
 I thought about this, but decided to copy the whole project each time. What do you think?

**I think this is handier but given we are not going to have many more updates I think it is fine.**

**Comment by dandrewstewart** [comment]
How do you "git pull"?  Is this command line?  And do I use command line to create a clone?  Also, in your message, above (and in previous messages) why are some words in smaller font, on a grey background?  This is a feature of the typography in Github, yes?
