### ISSUE TITLE
audio source (VISUAL AND AUDIO)

### ISSUE THREAD

**Issue by dandrewstewart** [panavrin/live-writing-osc#12]
I think you have already tested audio source (visual) with an audio card/interface, yes?  I was hoping to run audio from Ableton into LW.  My MOTU Ultralite permits a "rewired" input;  that is to say, I can send audio back to my laptop using this rewired input, without causing feedback in my system.  When I select MOTU in audio source (visual), the response of the text in Chrome doesn't seem to correspond to what Ableton is sending.  Instead, the text responds exactly as if my internal microphone was activated.  

I will try again, tonight.  And in any case, I can make do with the latest version of LW, if you don't have time to test drive this feature.  No problems.  Thought I would mention it, in case a bug has developed.

In the attached photo, you also see MOTU selected for audio source (audio), but I probably won't use this for the performance.  Instead, I plug a microphone into my MOTU and record/manipulate audio in Ableton.  No need to do it in LW. 

<img width="729" alt="screen shot 2017-05-04 at 20 09 55" src="https://cloud.githubusercontent.com/assets/28174995/25731723/11704aaa-3106-11e7-8dc5-b4310d0411a4.png">

**Comment by dandrewstewart** [comment]
That didn't take long to confirm a bug … lots of feedback, squealing, from my loudspeakers.  Yikes!  So, I can confirm that when I chose my audio interface (MOTU) for audio source (audio), Chrome "continues" to use the internal microphone.  I'm sure that in previous versions I was able to choose MOTU and I did not get feedback.  So, selecting audio source (audio and visual) both appear to have a bug – the internal microphone remains active.  Again, I can work around this.  However, it would be nice to have audio source (visual) functioning so that I can drive the text visual effects with sound received 'only' from Ableton.  I hope this helps

**Comment by panavrin** [comment]
so I guess the buzz sound is coming from this audio routing right? 
I wonder if you can use soundflower for this.

So how it works is Ableton send sound to SoundFlower (instead of MOTU) 
and soundflower is routed to your MOTU interface. 

And then LW can hijack the output from SoundFlower for audio source(visual) and it is direct sound so it won't have any feedback.  

https://youtu.be/lRPaYCpXhYk?t=71

**Comment by panavrin** [comment]
so I think if you chose my audio interface (MOTU) for audio source (audio), LW will pick up sound from MOTO and your computer eventually send sound to MOTO. 

As long as you do not use audio source(audio), I believe there will be no feedback. is this right? 
you do not have to select it.

**Comment by dandrewstewart** [comment]
I may run some tests with SoundFlower, which I've used a lot in the past.

**Comment by panavrin** [comment]
Hi, Andrew. 

I found the error with the audio source (audio). 

It is because the web audio standard changes over time. 

The code that you have always use the built-in laptop microphone, which could have been the issue. 

I updated the code so you will be able to use something else.
