### ISSUE TITLE
Sound with /add hello

### ISSUE THREAD

**Issue by dandrewstewart** [panavrin/live-writing-osc#13]
Would it be easy to add the key stroke sounds when sending characters from App to LW?  In my case, I will be sending one character at a time and not words (e.g.,   /add h    /add e     /add l    /add l      /add o).  I suppose that if a whole word is added, the keystroke sound could be triggered by, say, the first (or last) letter of the word.  What do you think?  Again, this is not 'super' necessary.

**Comment by panavrin** [comment]
not too difficult. I will do it shortly.

**Comment by panavrin** [comment]
done!

**Comment by dandrewstewart** [comment]
I think that's it, Sang.  **_LET'S FREEZE DEVELOPMENT._**   I really need to start working on mapping MYO data and I believe you've given me a lot to work with.  Thanks.. !!!

**Comment by panavrin** [comment]
Sure. I will freeze coding only because to give you some space and time.

However, feel free to request more.

Also, I guess the buzzing thing is resolved?

Sang
