### ISSUE TITLE
/add text feedback loop

### ISSUE THREAD

**Issue by dandrewstewart** [panavrin/live-writing-osc#15]
Here's one issue, Sang, that would be worth looking at; but I can work around it.  I send text from my App to LW on port 3333.  Next, LW mirrors this text entry and sends it back to my App on port 3334.  For the moment, I think this is creating a bit of havoc in my Max patch, which I can work around. In the future, I could imagine some interesting applications will multiple computers.  However, in this case, how about either:  disabling this mirrored/returned signal back to the App;   or create an OSC Address for enabling/disabling this feedback feature (e.g., /add/feedback 0 or 1 to disable or enable).  Does this make sense?

**Comment by panavrin** [comment]
the feedback loop is removed.

**Comment by dandrewstewart** [comment]
I believe a 'bug' was introduced with your last modification. The "feedback loop" no longer exists.  So, that's great! 

But now, after I send an /add hello from my App to LW, the path from LW to App is disabled.  For example, 1st, I send /add hello.  2nd, when I return to Chrome and type normally, the data is not being received by my App on port 3334 – the "/added" data isn't reaching my App. I can report that this only affects "/added"  (and probably /removed). However /key continues to work – I continue to receive /key on port 3334.

Am I explaining myself clearly?   Help

**Comment by panavrin** [comment]
Oops my bad. this is fixed.
