### ISSUE TITLE
(4.2) Incremental shifting of entire text

### ISSUE THREAD

**Issue by dandrewstewart** [panavrin/live-writing-osc#19]
For this, we return to OSC messaging. Firstly, I believe I could achieve the following in Max, but I am also wondering if there might be an implementation in the LW programming, too.  Essentially, would it be possible to send an OSC message that moves the entire text incrementally up, down, left right?  By "incrementally", I mean could an OSC message "nudge" the entire text in a particular direction.  I am asking because I'd like to use a "swiping" gesture to nudge/push the text JUST A LITTLE BIT from side to side, up and down.  Again, I think I can do this with MYO data and Max, too.  What do you think? Or a better variation:  the "nudge" may be small or large based on the force of my physical gesture.  What do you think?

**Comment by panavrin** [comment]
I can do this but another way to do is to move the camera to one direction (using  `\camtranslate`) so that the entire text could move to the other direction. Maybe you know they those two can be different?

**Comment by dandrewstewart** [comment]
Great idea
