### ISSUE TITLE
Tethered text

### ISSUE THREAD

**Issue by dandrewstewart** [panavrin/live-writing-osc#20]
Here is another distortion/dynamic typography that would be really awesome, especially if we could control it with some incoming OSC messages.  After (or during) the writing of the text, could the text be pushed and pulled around on the screen, always returning to its original position – as if each character is "tethered" to its spot in a word and in a sentence.  I would love to have a physical pushing/pulling gesture that momentarily moves the text (scrambles) it and then, the text returns to its original position.  Maybe another analogy would be repulsion and attractive forces – some characters moving toward or away from specific characters, etc.

**Comment by panavrin** [comment]
Again, I think this can be done using `\camtranslate`. For example, if camtranslate can be fed with sine wave amplitude over time (let's say 1hz frequency) in z-axis the entire text should go back and forth (in fact the camera is going back and forth).

**Comment by dandrewstewart** [comment]
Excellent idea.
