### ISSUE TITLE
(4) activating background drones

### ISSUE THREAD

**Issue by panavrin** [panavrin/live-writing-osc#4]
(4)  Similarly to activating the sounds for each key stroke (with "question mark"), could the low (and high) background drones/tones also be activated/deactivated with a particular key stroke? I suggest:

! = activate/deactivate background drones/tones

**Comment by panavrin** [comment]
Not entirely sure which sound you are referring? When is it first heard? Is it triggered by a key or is it constant sound in the background? If so when is it first heard?

**Comment by dandrewstewart** [comment]
You are correct … I am referring to the 1st sound you hear – long tones.  However, for each page, the long tones are always present.  Sometimes they do seem to be consonant, but for the most part, they are either very low and, thus, they act as a "bass" voice;  or they are very high – so high that they seem to be an "effect" and not really part of any underlying harmonic idea.  If possible, could one keystroke (exclamation mark) be used to deactivate all "long tones", whether they are consonant or not?

**Comment by panavrin** [comment]
This is done. Please check. 

The default value is false, which means that you need to press `!` to turn on the drone sound. Let me know if you want it to be true by default.

**Comment by dandrewstewart** [comment]
Exclamation mark appears to have no effect.  I can only get a long tone(s) by pressing question mark and then, the tone(s) are only high, which is actually fine – less obtrusive than the low bassy tones.

**Comment by panavrin** [comment]
Do you want to turn off the long tone which is played when you press the question mark?

**Comment by dandrewstewart** [comment]
Yes please.  Ideally, could the question mark activate/deactivate "only" the keystroke sounds? Thanks

**Comment by panavrin** [comment]
Please check if this works as you wanted.

**Comment by dandrewstewart** [comment]
When pressing exclamation point, is it possible to add, say, a 100 millisecond fade (in and out) of the sound.  Presently, I can hear a digital click as I activate/deactivate long tones. This not too dramatic because, as you probably remember, I run ALL sound through Ableton.  So, with some effects (including reverb) the digital click is not too disturbing.

**Comment by dandrewstewart** [comment]
I believe, on page 2, an additional background drone is initiated – its sound quality is a bit like the buzzing/humming of an electrical circuit.  I think it also slowly fades out during page 3.  Do you know the one?  Could this layer also be activated/deactivated with exclamation mark?

**Comment by panavrin** [comment]
The digital click is removed now. 

Not sure about the additional background drone at page 2. Do you mean the sound of which pitch changes line by line? if that's what you mean, it is initiated by the first question mark and then it will be toggled by the exclamation mark. or is this some other kinds of sound?

**Comment by dandrewstewart** [comment]
I think we may need to do a SKYPE, where we can listen to the sounds together.  Alternatively, if it's easier for you, the best solution may be to eliminate all sounds except for two:  (1) discrete sounds for each key stroke and (2) the vocal samples on page 3.  If this is easy for you, let's try this.  Does this make sense?

**Comment by panavrin** [comment]
The latter needs too many changes. Do you want to do a skype now? Or you could send me a (private youtube) video with the timestamp explaining the sound? Do you turn on the Audio Source (audio)?

**Comment by dandrewstewart** [comment]
You know what…let me play around with the current version a bit more, if you don't mind. Perhaps the sound that resembles a humming/buzzing circuit will be fine.  I have noticed that it has a specific duration – it does eventually fade out.  Instead, if you have any more time for this project, I think it'd be great to look at either issue no. 5 or 6.  If you think you have reached your limit, that's fine too.

**Comment by dandrewstewart** [comment]
Hi Sang … I have just e-mailed you a very short audio file (Thursday, 5:45pm, your time).  You'll hear what I call the electrical buzz/hum.  I have noted that this buzz has a duration – it isn't on all the time.  However, if you think it is easy, about assigning hashtag  (  #  )  to activate/deactivate this layer.  If it's too much work, don't worry about it !!

**Comment by panavrin** [comment]
Hi, Andrew. I heard the audio but I couldn't spot that audio when I run it. Is the sound present from the beginning when you don't type anything at all? Or is it present when you type something and make some progress in the page. 

another question is do you use a microphone when you perform? what do you choose in Audio Source (audio) drop down menu?

**Comment by panavrin** [comment]
A reason why I am asking is that I wonder if you can hear the buzz even when you do not select an audio source(audio). Could you try that? If you could capture your screen for me to know how you get there to play the buzz will be helpful.

**Comment by dandrewstewart** [comment]
In the audio excerpt I sent you by e-mail, the electronic buzz was "on" all the time.  It was the sound that was constant.  In the excerpt, I also types a few keys and I also activated the upper drone with (!).  But the lower buzz drone was always present.

I don't think it is related to audio source(audio), because the buzz (a drone) evolves – it comes in at certain moments and then slowly fades out after several minutes.  It also has overtones from time to time.  So, I think it is one of the layers you programmed.  I will run tests with audio source(audio), but to answer your question, I don't use audio source(audio) and I don't think I will use it in the performance.

**Comment by dandrewstewart** [comment]
I'm moving this topic [audio source(audio)] to its own issue
