### ISSUE TITLE
(6) flashing strobing

### ISSUE THREAD

**Issue by panavrin** [panavrin/live-writing-osc#6]
(6)  Flashing/strobing of the Chrome browser background, and the shading of the text would change concurrently so that the text always remains visible.  The strength of contrast could vary – at times, a true white against black, or grey against grey.  With respect to mapping this visual effect, I could imagine three mappings to:  (1)  activate/deactivate effect,   (2) change strength of contrast and,  (3) change rate of flashing/strobing.

**Comment by panavrin** [comment]
I think the right thing to do is to inverse the color (black background, white fonts) from the current version. What do you think?

**Comment by dandrewstewart** [comment]
Sure.  Go for it!  Let's take a look.

**Comment by panavrin** [comment]
I think this is done. 

to change the background send `/color 0` for white background send `/color 1`

to change the font color send `/color 0` (for black) or send `/color 1`

**Comment by panavrin** [comment]
In fact, I changed the scale to the value between 0 and 1

**Comment by dandrewstewart** [comment]
You wrote:

> to change the background send /color 0 for white background send /color 1
> to change the font color send /color 0 (for black) or send /color 1

…but these are the same OSC addresses.  Did you mean:  /color and /fontcolor ?

**Comment by panavrin** [comment]
Oops fontcolor
