### ISSUE TITLE
(7) audio routing

### ISSUE THREAD

**Issue by panavrin** [panavrin/live-writing-osc#7]
(7)  Separating each of the native audio layers into their own stereo outputs:  long tones/drones, keystroke sounds, the sounds being picked up by "audio source audio". It would be nice to sample the keystroke sounds without sampling any other sounds.

**Comment by dandrewstewart** [comment]
I don' think this is a significant issues, now that I can deactivate layers with:   !   .  And maybe you can work on the buzz (  #  ) , if it isn't too complicated.
