### ISSUE TITLE
(3) camrotate range coupled with zoom

### ISSUE THREAD

**Issue by dandrewstewart** [panavrin/live-writing-osc#8]
Thanks Sang. Very nice. I'm making headway on the sound ideas, while you are modifying the programming. Where does "translate" come from, in /camtranslate.  Is this named after a particular principle in, say, physics or geometry?

- Could /zoom be created (instead of /zoomin and /zoomout) AND use the same absolute value system as /camrotate?

- Could we have one consistent range for the axes of /camrotate?  For example, I have noticed that with "no" zoom applied, the range of values for each axis of /camrotate is from 0. to 7.47 (or the same range in negative values).  This means, with no zoom, sending values from 0. to 7.47 rotates the text the full 360 degrees – aside, I thought this might mathematically related to, expressed in, radians, or something like that, but I don't think this is the case. Next, if zoom is applied, for example, zooming out, the range (0. to 7.47) is considerably reduced. The text rotates the full 360 degrees at a smaller value than 7.47.  This is obviously about the math;  however, from my end, having one consistent range (e.g., 0. to 7.47) would make the mapping easier, especially if I want to apply /zoom simultaneously.

**Comment by panavrin** [comment]
probably geometry in 3d space. basically it means the camera (your eye) moves in the x-y-z space. 

https://en.wikipedia.org/wiki/Translation_(geometry) 

I will do both tonight. Also could you close the issues that are resolved?

**Comment by panavrin** [comment]
1 --> 180 degree -1 --> -180 degree. 
zoom also takes a parameter. positive : zoomin , negative : zoomout

**Comment by dandrewstewart** [comment]
Right on!
